# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/triathlon" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

contact_phone: +7 912 123 45 00
contact_email: test@test.ru

contact_social_facebook: https://facebook.com
contact_social_instagram: https://www.instagram.com/triatlon_goldnik
contact_social_youtube: https://www.youtube.com/channel/UCUXyZhKmxe-21xOnhqbWFjg


# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed

kramdown:
  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#  css_class: 'highlight'

#sass:
#  style: :expanded

# Exclude from processing.
exclude: [
  '.idea/',
  'node_modules', '_scripts', '_dev',
  'README.md', 'DEV_GUIDE.md',
  'gulpfile.js', 'package.json', 'package-lock.json', 'yarn.lock',
  'LICENSE',
  '.editorconfig'
]

collections:
  coach:
    output: true
  report:
    output: true


defaults:
  - scope:
      path: ""
      type: coach
    values:
      layout: coach
      nav_light: COACHES
  - scope:
      path: ""
      type: report
    values:
      layout: report
      nav_light: REPORTS
